function weakly_show_state(iter, max_iter, train_results)
    fprintf('\n------------------------ %10s Iteration %4d / %4d -------------------------\n', datestr(datevec(now()), '[yyyy:mm:dd]@[HH:MM:SS]'), iter, max_iter);
    fprintf('Training : accuracy %.3g, loss (cls %.3g, reg %.3g)\n', ...
        mean(train_results.accuarcy.data), ...
        mean(train_results.loss_cls.data), ...
        mean(train_results.loss_bbox.data));
end
